config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile' , as: :profile
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    member do
      get :confirm_email
    end
  end
  get "pages/schedule"
  get "pages/invitation"
  get "pages/loading"
  get "no_film", to: "pages#no_film", as: "no_film"
  get "friends", to: "pages#friends", as: "friends"
  get "my_events", to: "pages#my_events", as: "my_events"
  post "friends/request", to: "users#request_friend", as: "request_friend"
  get "friends/delete/:id", to: "users#delete_friend", as: "delete_friend"
  get "friends/accept/:id", to: "users#accept_friend", as: "accept_friend"
  get "friends/decline/:id", to: "users#decline_friend", as: "decline_friend"
  get "events/:id/answer", to: "events#answer", as: "answer"
  get "events/:id/final", to: "events#final", as: "final"
  get "guests/:id/confirm", to: "guests#confirm", as: "confirm"
  get "guests/:id/decline", to: "guests#decline", as: "decline"
  get "events/:id/result", to: "events#result", as: "result"

  resources :events, only: [:show, :new, :create, :destroy]
  resources :films, only: [:show, :new, :create, :index]
  resources :films do
    resources :favorites, only: [:new, :create, :destroy]
  end
  resources :favorites, only: [:index, :destroy]

  resources :reviews, only: [:show, :edit, :update, :destroy]
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    patch "draganddrop", to: "favorites#sort"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  acts_as_list scope: :user
  belongs_to :film

  validates :film, presence: true
  validates :user, presence: true
end

app/controllers/api/favorites_controller.rb
class Api::FavoritesController < ApplicationController
  def sort
    params["_json"].each_with_index do |favorite_id, index|
      # params => { favorites: [2, 3, 12] }
      Favorite.where(id: favorite_id.to_i).update_all(position: index + 1)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_film, only: [:show, :destroy]

  def index
    # @friend_requests = current_user.requested_friends
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.create!(user_id: current_user.id, film_id: params[:film_id])
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_path
  end

  def show
  end

  private

  def favorites_params
    params.require(:favorite).permit(:user_id, :film_id)
  end

  def set_film
    @film = Favorite.find(params[:id])
  end
end

app/views/favorites/index.html.erb
<h1 class="text-center color">Ma liste d'envies (<%= current_user.films.count %>)</h1>
<div class="fav-advise">
  Vous pouvez ici classer vos films à voir selon votre ordre de préférence. Plus le film est haut, plus il aura de chance d'être choisi lors de votre prochaine sortie !
  <br>
  Pour les classer, il suffit de les faire glisser de haut en bas pour les trier.
</div>
<% if current_user.favorites.count < 3 %>
  <div class="alert-film">
    <strong>Attention !</strong> Votre liste de film n'est pas assez fournie pour organiser une sortie. ( Minimum 3 films ) Ajoutez en d'autres en cliquant
    <%= link_to "ICI", root_path, style: "color: black" %>
  </div>
<% end %>
<div class="favorites pt-4" id="favorite" data-url="<%= api_draganddrop_path %>">
  <% current_user.favorites.each_with_index do |favorite, index| %>
    <div data-id="<%= favorite.id %>" class="d-flex justify-content-between align-items-center mb-1" id="favsortable">
      <div>
        <%= image_tag favorite.film.photo_url, style: "height: 100px; width: 70px;" %>
      </div>
      <p><%= favorite.film.title %></p>
      <div d-flex justify-content-between>
        <%= link_to "", favorite_path(favorite),
                    method: :delete,
                    class: "fas fa-times fa-2x remove-fav" %>
        <i class= "fas fa-bars p-2"></i>
      </div>
    </div>
  <% end %>
</div>
<div class="text-center my-4">
  <%= link_to "Ajouter d'autres films", root_path, class: "btn btn-primary bungee box-shadow" %>
</div>