config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile' , as: :profile
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    member do
      get :confirm_email
    end
  end
  get "pages/schedule"
  get "pages/invitation"
  get "pages/loading"
  get "no_film", to: "pages#no_film", as: "no_film"
  get "friends", to: "pages#friends", as: "friends"
  get "my_events", to: "pages#my_events", as: "my_events"
  post "friends/request", to: "users#request_friend", as: "request_friend"
  get "friends/delete/:id", to: "users#delete_friend", as: "delete_friend"
  get "friends/accept/:id", to: "users#accept_friend", as: "accept_friend"
  get "friends/decline/:id", to: "users#decline_friend", as: "decline_friend"
  get "events/:id/answer", to: "events#answer", as: "answer"
  get "events/:id/final", to: "events#final", as: "final"
  get "guests/:id/confirm", to: "guests#confirm", as: "confirm"
  get "guests/:id/decline", to: "guests#decline", as: "decline"
  get "events/:id/result", to: "events#result", as: "result"

  resources :events, only: [:show, :new, :create, :destroy]
  resources :films, only: [:show, :new, :create, :index]
  resources :films do
    resources :favorites, only: [:new, :create, :destroy]
  end
  resources :favorites, only: [:index, :destroy]

  resources :reviews, only: [:show, :edit, :update, :destroy]
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    patch "draganddrop", to: "favorites#sort"
  end
end

app/views/shared/_banner.html.erb
<div class="banner-image">
  <div class="row">
    <div class="banner-text col-sm-6">
      <h1>Tu veux organiser une sortie cinéma facilement ?</h1>
      <%= link_to "J'organise mon ciné !", new_event_path, class: "banner-btn bungee color" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <!-- <a href="#"><i class="fab fa-github"></i></a> -->
    <a href="https://www.instagram.com/gocineclub/" target="-blank"><i class="fab fa-instagram"></i></a>
    <a href="https://github.com/AmineNGB/Gocine" target="-blank"><i class="fab fa-github"></i></a>
    <!-- <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a> -->
    <!-- <a href="#"><i class="fab fa-linkedin"></i></a> -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %> <%= image_tag "logo.png" %> <% end %>
    <!-- <%= link_to new_event_path, class: "navbar-plus" do %>
  <%= image_tag "plus.svg" %>
  <% end %> -->
    <div class="nav-btn">
      <% if user_signed_in? %>

      <div class="star btn-nav">
        <%= link_to favorites_path, class: "navbar-clip" do %> <%= image_tag "heart.svg" %>
        Mes envies <% end %>
      </div>
      <div class="friends-icon btn-nav">
          <% if current_user.requested_friends.count > 0 %>
            <div class="notification-badge friends-notification">
              <%= current_user.requested_friends.count %>
            </div>
          <% end %>
        <%= link_to friends_path, class: "navbar-clip" do %> <%= image_tag "friends.svg" %>
          Amis <% end %>
      </div>
      <% end %>
      <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >

        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= image_tag "scream.svg", class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true,
                                          'aria-expanded': false %>
            <% if current_user.pending_events.count > 0 %>
              <div class="notification-badge events-notification">
                <%= current_user.pending_events.count %>
              </div>
            <% end %>
              <div
            class="dropdown-menu dropdown-menu-right mt-3"
            aria-labelledby="navbarDropdown"
          >

                <%= link_to "Mon compte", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Ma liste de films", favorites_path, class: "dropdown-item" %>
                <%= link_to "Mes sorties", my_events_path, class: "dropdown-item" %>
                <% if current_user.pending_events.count > 0 %>
                  <div class="notification-badge events-notification-list">
                      <%= current_user.pending_events.count %>
                  </div>
                <% end %>
                <%= link_to "Organiser un ciné", new_event_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, method: :get, class: "dropdown-item" %>
              </div>
              <i class="fas fa-caret-down" id="triangle"></i>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>