config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile' , as: :profile
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    member do
      get :confirm_email
    end
  end
  get "pages/schedule"
  get "pages/invitation"
  get "pages/loading"
  get "no_film", to: "pages#no_film", as: "no_film"
  get "friends", to: "pages#friends", as: "friends"
  get "my_events", to: "pages#my_events", as: "my_events"
  post "friends/request", to: "users#request_friend", as: "request_friend"
  get "friends/delete/:id", to: "users#delete_friend", as: "delete_friend"
  get "friends/accept/:id", to: "users#accept_friend", as: "accept_friend"
  get "friends/decline/:id", to: "users#decline_friend", as: "decline_friend"
  get "events/:id/answer", to: "events#answer", as: "answer"
  get "events/:id/final", to: "events#final", as: "final"
  get "guests/:id/confirm", to: "guests#confirm", as: "confirm"
  get "guests/:id/decline", to: "guests#decline", as: "decline"
  get "events/:id/result", to: "events#result", as: "result"

  resources :events, only: [:show, :new, :create, :destroy]
  resources :films, only: [:show, :new, :create, :index]
  resources :films do
    resources :favorites, only: [:new, :create, :destroy]
  end
  resources :favorites, only: [:index, :destroy]

  resources :reviews, only: [:show, :edit, :update, :destroy]
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    patch "draganddrop", to: "favorites#sort"
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :guests
  has_many :users, through: :guests
  belongs_to :seance, optional: true
  belongs_to :cinema
  has_one :film, through: :seance
  accepts_nested_attributes_for :guests

  # enum schedule: [:matin, :apresmidi, :soir]

  validates :date, presence: true
  validates :schedule, presence: true
  validates :endschedule, presence: true
  validates :cinema_id, presence: true
  validate :schedule_must_be_lower_than_endschedule
  validate :event_cant_be_in_past
  validate :event_cant_be_in_more_than_7_days

  def event_cant_be_in_more_than_7_days
    if date != nil
      if date > Date.today + 7
        errors.add(:date, "Vous ne pouvez pas créer un évenement dans plus d'une semaine")
      end
    end
  end

  def event_cant_be_in_past
    if date != nil
      if date < Date.today
        errors.add(:date, "Vous ne pouvez pas créer d'évenement dans le passé")
      end
    end
  end

  def schedule_must_be_lower_than_endschedule
    if schedule != nil && endschedule != nil
      if schedule > endschedule
        errors.add(:schedule, "L'heure du début doit être avant la fin ..")
      end
    end
  end

  def good_movies
    Seance.where(horaire: hours_range, cinema_id: cinema_id)
  end

  def hours_range
    # if matin?
    #   date.to_datetime.change(hour: 10)..date.to_datetime.change(hour: 13)
    # elsif apresmidi?
    #   date.to_datetime.change(hour: 13)..date.to_datetime.change(hour: 18)
    # elsif soir?
    #   date.to_datetime.change(hour: 18)..date.to_datetime.change(hour: 23)
    # end
    date.to_datetime.change(hour: self.schedule)..date.to_datetime.change(hour: self.endschedule)
  end

  def date_fr
    date.strftime("%A %d %B")
  end

  def creator
    self.guests.last.user
  end

  def participants
    guests = self.guests.reject { |guest| guest.status != "confirmed" }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    # @friend_requests = current_user.requested_friends
  end

  def show
    @event = Event.find(params[:id])
    # @friend_requests = current_user.requested_friends
  end

  def new
    # @friend_requests = current_user.requested_friends
    if current_user.favorites.count < 3
      flash[:alert] = "Vous devez avoir au moins 3 films dans votre liste"
      redirect_to favorites_path
    end
    @event = Event.new
  end

  def create
    # @friend_requests = current_user.requested_friends
    @friends = current_user.friends
    @event = Event.new(event_params)

    @event.save

    if @event.save
      @event.guests.create!(user_id: current_user.id, status: "confirmed")
      url = answer_url(@event.id)
      @guests = @event.guests.reverse.drop(1).reverse
      @guests.each do |guest|
        UserMailer.with(event: @event, url: url, guest: guest).ask_for_event.deliver_later
      end
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
  end

  def result
    # @friend_requests = current_user.requested_friends
    @event = Event.find(params[:id])
    seance = MovieMatcher.new(@event).find_best_seance
    if seance == 0
      redirect_to no_film_path
      return nil
    end
    @event.seance = seance
    @event.save!
    @seance = Seance.find(@event.seance_id)
    participants = @event.participants
    participants.each do |guest|
      UserMailer.with(guest: guest, event: @event).final.deliver_later
    end
    redirect_to final_path
  end

  def answer
    # @friend_requests = current_user.requested_friends
    @event = Event.find(params[:id])
    # url = answer_url
    # UserMailer.ask_for_event(@event, url).deliver
  end

  def final
    # @friend_requests = current_user.requested_friends
    @event = Event.find(params[:id])
    # guest = @event.guests.find_by(user: current_user)
    # guest.confirmed!
  end

  private

  def event_params
    params.require(:event).permit(:schedule, :endschedule, :users, :cinema_id, :date, user_ids: [])
  end
end

app/views/events/answer.html.erb
<div class="header-answer color">
  <h2 class="header-answer align-items-center bungee"><%= l @event.date, format: :long %> </h2>
  <h2 class="header-answer align-items-center bungee"><%= @event.cinema.name %> </h2>
</div>
<% @event.guests.each do |guest| %>
  <div class=" answer-card ">
    <h3 class="d-flex align-items-center"><%= User.find(guest.user_id).prenom %> <%= User.find(guest.user_id).nom %></h3>
    <% if guest.status == "confirmed" %>
      <div class="d-flex align-items-center">
        <i id="confirmed" class="fas fa-check-circle fa-3x"></i>
      </div>
    <% elsif guest.status == "rejected" %>
      <div class="d-flex align-items-center">
        <i id="declined" class="fas fa-times fa-3x"></i>
      </div>
    <% elsif guest.user == current_user %>
      <div class="d-flex align-items-center">
        <%= link_to "Accepter", confirm_path(@event), class: "btn bungee btn-primary mr-2" %>
        <%= link_to "Refuser", decline_path(@event), class: "btn bungee btn-danger " %>
      </div>
    <% else %>
      <i id="pending" class="far fa-clock fa-3x d-flex align-items-center"></i>
    <% end %>
  </div>
<% end %>
<div class="d-flex justify-content-center mb-4">
  <% if @event.creator == current_user %>
    <%= link_to "Choisir le film", result_path(@event), class: "btn bungee btn-primary" %>
  <% else %>
    <%= link_to "Voir le film sélectionné", final_path(@event), class: "btn bungee btn-primary" %>
  <% end %>
</div>

app/views/events/final.html.erb
<% if @event.seance.present? %>
  <div id="center" class="mb-2">
    <div id="lock">
      <div class="color">
        <h1 class=""><strong>Votre séance</strong></h1>
        <h2 class=" bungee"><strong> <%= @event.seance.film.title %> </strong></h2>
      </div>
      <%= image_tag (@event.seance.film.photo_url), class: "affiche-finale fade-in" %>
      <div class="info enter-in">
        <div class="resume d-flex bd-highlight">
          <!-- <h4>Cinéma :</h4> -->
          <p class="bd-highlight"><strong><%= Cinema.find(@event.cinema_id).name %></strong></p>
          <!-- <h4>Horaire :</h4> -->
          <p class="ml-auto bd-highlight">
            <strong><%= Seance.find(@event.seance_id).horaire.time.to_formatted_s(:short) %></strong></p>
          <!-- <a><%= Seance.find(@event.seance_id).link %></a> -->
        </div>
        <div class="d-flex bd-highlight">
          <div>
            <h4 class="bd-highlight">Avec :</h4>
          </div>
          <div class=" ml-auto bd-highlight font-weight-bold">
            <% @event.participants.each do |guest| %>
              <% user = guest.user %>
              <p><%= user.nom %>
                <%= user.prenom %></p>
            <% end %>
          </div>
        </div>
        <a target="_blank" class="btn bungee btn-primary mt-4" href="<%= Seance.find(@event.seance_id).link %>">Réservez ici !</a>
      </div>
      <!-- <h3>Bon Film !</h3> -->
    </div>
  </div>
<% else %>
  <div class="d-flex flex-column justify-content-center text-center mt-4" id="loading">
  </div>
  <h3 class="d-flex justify-content-center text-center mt-4">Veuillez patientez, l'organisateur doit lancer la recherche du film.</h3>
  <h5 class="d-flex justify-content-center text-center mt-4">Vous receverez un e-mail lors du choix final.</h5>
<% end %>

app/views/events/new.html.erb
<div class="forms">
  <div class="event-form">
    <%= simple_form_for(@event) do |f| %>
      <%= f.input :date, as: :date, html5: true, order: [:day, :month, :year], label: "Date de sortie" %>
      <% #= f.input :schedule, wrapper: :vertical_collection_inline, wrapper_html: { class: "radio-horaire" }, collection: [['Matin', :matin], ['Après-midi', :apresmidi], ['Soir', :soir]], as: :radio_buttons, label: "Plage horaire:" %>
      <p class="col-form-label">Plage horaire du début de la séance *</p>
      <%= f.input :schedule, collection: 9..23, prompt: "Début", label: false %>
      <%= f.input :endschedule, collection: 9..23, prompt: "Fin", label: false %>
      <%= f.input :cinema_id, collection: Cinema.pluck(:name, :id), input_html: { class: "selectpicker", title: "Choisissez votre cinéma", "data-live-search" => "true" }, label: "Cinema" %>
      <%= f.input :user_ids, as: :select, collection: current_user.friends, input_html: { multiple: true, class: "selectpicker", title: "Invitez vos amis", "data-live-search" => "true", "data-max-width" => "28rem", "data-actions-box" => "true" }, label: "Avec qui veux-tu y aller ?" %>
      <%= f.submit "Créer cet événement !", class: "btn bungee btn-primary submit mt-2 shadow-lg" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="d-flex flex-column justify-content-center align-items-center">
    <h1 class="color">Partage à tes amis</h1>
    <h4 class="mt-3">Tes amis ont été invités par e-mail, tu peux aussi les inviter, en copiant le lien, par un autre réseau social:</h4>
    <textarea readonly="readonly" id="to-copy" spellcheck="false"><%= answer_url %></textarea>
    <button class="btn bungee btn-primary" id="copy" type="button">Copie le lien<span class="copiedtext" aria-hidden="true">Copié</span></button>
    <h4 class="mt-5">Une fois tes amis invités, clique sur "Suivant"</h4>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to "Suivant", answer_path, class: "btn bungee btn-primary" %>
    </div>
</div>