config/routes.rb
Rails.application.routes.draw do
  # get 'users/profile' , as: :profile
  default_url_options host: "localhost:3000"
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users do
    member do
      get :confirm_email
    end
  end
  get "pages/schedule"
  get "pages/invitation"
  get "pages/loading"
  get "no_film", to: "pages#no_film", as: "no_film"
  get "friends", to: "pages#friends", as: "friends"
  get "my_events", to: "pages#my_events", as: "my_events"
  post "friends/request", to: "users#request_friend", as: "request_friend"
  get "friends/delete/:id", to: "users#delete_friend", as: "delete_friend"
  get "friends/accept/:id", to: "users#accept_friend", as: "accept_friend"
  get "friends/decline/:id", to: "users#decline_friend", as: "decline_friend"
  get "events/:id/answer", to: "events#answer", as: "answer"
  get "events/:id/final", to: "events#final", as: "final"
  get "guests/:id/confirm", to: "guests#confirm", as: "confirm"
  get "guests/:id/decline", to: "guests#decline", as: "decline"
  get "events/:id/result", to: "events#result", as: "result"

  resources :events, only: [:show, :new, :create, :destroy]
  resources :films, only: [:show, :new, :create, :index]
  resources :films do
    resources :favorites, only: [:new, :create, :destroy]
  end
  resources :favorites, only: [:index, :destroy]

  resources :reviews, only: [:show, :edit, :update, :destroy]
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    patch "draganddrop", to: "favorites#sort"
  end
end

app/views/pages/final.html.erb
<div id="center">
  <div id="lock">
    <h1 id="zest"><strong>Votre soirée</strong></h1>
    <%= image_tag (@event.seance.film.photo_url), class: "tof", size: "180x240" %>
    <div class="info">
      <p><strong><%= Cinema.find(Event.last.cinema_id).name %></strong></p>
      <p><strong><%= I18n.l(@date, format: :long, locale: :'fr') %></strong></p>
      <% Event.last.users.each do |user| %>
      <div class="d-flex justify-content-center font-weight-bold">
        <%= user.nom %> <%= user.prenom %>
      </div>
      <% end %>
    </div>
    <h3>Bon Film !</h3>
  </div>
</div>

app/views/pages/friends.html.erb
<h1 class="text-center color"><strong>Mes Amis</strong></h1>
<div class="friends-pages d-flex">
  <div class="friends-list">
    <ul class="list-group friends-list">
      <h3>Amis</h3>
      <% if @friends.empty? %>
        <div class="alert-film" role="alert">
          Vous n'avez encore aucun ami ! <strong>Ajoutez en !</strong>
        </div>
      <% end %>
      <% @friends.each do |friend| %>
        <li class="list-group-item friend-line">
          <%= friend.prenom + " " + friend.nom %>
          <div>
            <%= link_to "", delete_friend_path(friend.id), title: "Supprimer cet ami", data: { confirm: "Es tu
                                          sur de vouloir supprimer #{friend.prenom} de tes amis ?" }, class: "fa
                                          fa-user-alt-slash", style: "color: red; text-decoration: none" %>
          </div>
        </li>
      <% end %>
    </ul>
    <br />
    <% if @friend_requests.count > 0 || @pending_friends.count > 0 %>
      <ul class="list-group friends-list">
        <h3>En attente</h3>
        <% @friend_requests.each do |friend| %>
          <li class="list-group-item friend-line">
            <%= friend.prenom + " " + friend.nom %>
            <div class="d-flex">
              <div>
                <%= link_to "", accept_friend_path(friend.id), title: "Accepter la demande", class: "fa fa-check",
                                                               style: "color: green; font-size: 20px; text-decoration: none" %>
              </div>
              <div>
                <%= link_to "", decline_friend_path(friend.id), title: "Refuser la demande", class: "fa fa-times
                                                    ml-4", style: "color: red; font-size: 20px; text-decoration: none" %>
              </div>
            </div>
          <% end %>
        </li>
        <% @pending_friends.each do |friend| %>
          <li class="list-group-item friend-line disabled ">
            <%= friend.prenom + " " + friend.nom %>
            <div class="fa fa-clock ml-4">
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="friends-form">
    <h3>Ajouter un ami</h3>
    <%= form_with(url: request_friend_path, method: "post", html: { class: "form-group" }, local: true) do %>
      <%= text_field_tag(:email, "", class: "form-control", placeholder: "toto@email.com") %>
      <%= submit_tag("Ajouter !", class: "btn bungee btn-primary mt-2") %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="cinema-filter">
  <%= simple_form_for :query, url: root_path, method: "GET", html: { class: "form-filter" } do |f| %>
  <%= f.input :id, as: :select, collection: Cinema.all.order("name ASC"), input_html: { class: "selectpicker form-control", "data-live-search" => "true", value: "Toto", placeholder: "" }, label: "Choisissez votre cinéma", prompt: "Tous", required: false %>
  <%= f.submit "Choisir", class: "btn bungee btn-primary" %>
  <% end %>
  <p class="mt-4 info-home alert-film">Nous avons pour le moment seulement les gros cinémas de Lyon de disponibles, mais si vous en désirez un autre, n'hésitez pas à nous contacter par mail : <a href="mailto:gocineclub@gmail.com">gocineclub@gmail.com</a></p>
</div>
<div class="color">
  <h1>A l'affiche</h1>
</div>
<div class="cinema-name">
  <% if @cinema.present? %>
    <h2 class="color2 bungee"><%= @cinema.name %></h2>
  <% end %>
</div>
<div class="fav-advise">
  Vous pouvez ici voir les films en ce moment à l'affiche dans les cinémas présents sur le site, ou dans le cinéma sélectionné s'il y en a un.
  <br>
  Il vous suffit d'ajouter les films que vous avez envie de voir à votre liste, en cliquant sur le bouton + .
  <br>
  Vous avez aussi la possibilité de cliquer sur une affiche pour avoir plus d'infos concernant le film en question.
  <br>
  Vous pourrez ensuite les classer dans votre ordre de préférence en allant voir votre liste d'envies, ou en cliquant
  <%= link_to "ICI", favorites_path, style: "color: black" %>
</div>
<div id="main">
  <% @films.each do |film| %>
    <div class="movie-card">
      <%= link_to film_path(film) do %>
        <%= image_tag film.photo_url, size: "160x200", class: "affiche-bord" %>
        <% if film.new? %>
          <p class="bungee new-icon">NEW !</p>
        <% end %>
        <% if film.top? %>
          <p class="bungee top-icon">5<i class="fas fa-star"></i></p>
        <% end %>
        <% if @favorites.include? film.id %>
        <% else %>
        <% if user_signed_in? %>
          <%= link_to film_favorites_path(film.id),
                      class: "plus-icon",
                      method: :post,
                      remote: true do %>
            <i class="fas fa-plus-square fa-3x"></i>
          <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/loading.html.erb
<div class="grostitre">
<p><strong>Votre film sera prêt dans ...</strong></p>
</div>
<div>
 <img src="https://media0.giphy.com/media/2XflxzDAw5pn6WaA372/giphy.gif?cid=ecf05e47b20f4084d7c4892b4d8dd762af3b6e21cee3a57b&rid=giphy.gif" alt="" order=0 width=100% height=400 >
</div>

app/views/pages/my_events.html.erb
<h1 class="text-center color">Mes Sorties</h1>
<h3 class="color2 bungee">Sorties à venir</h3>
<% if @pending_events.count > 0 %>
  <div class="events">
    <% @pending_events.each do |event| %>
    <div class="event-card">
      <div>
        <h4>Invités :</h4>
        <ul>
          <% event.guests.each do |guest| %>
          <li> <%= guest.user.to_s %> </li>
          <% end %>
        </ul>
      </div>
      <div>
        <h4>Cinéma :</h4>
        <%= event.cinema.name %>
      </div>
      <% if event.seance %>
      <div>
        <h4>Date :</h4>
        <%= l event.seance.horaire, format: :short %>
      </div>
      <div>
        <h4>Film :</h4>
        <%= event.seance.film.title %>
      </div>
      <% end %>
      <div class="show-event">
        <%= link_to "Réserver !", event.seance.link, target: :_blank, class: "btn bungee btn-primary" if event.seance %>
        <%= link_to "Répondre !", answer_path(event), class: "btn bungee btn-primary" if !event.seance %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
<% if @old_events.count > 0 %>
  <h3 class="color2 bungee">Sorties passées</h3>
  <div class="events">
    <% @old_events.each do |event| %>
    <div class="event-card">
      <div>
        <h4>Participants :</h4>
        <ul>
          <% event.participants.each do |guest| %>
          <li> <%= guest.user.to_s %> </li>
          <% end %>
        </ul>
      </div>
      <div>
        <h4>Cinéma :</h4>
        <%= event.cinema.name %>
      </div>
      <% if event.seance %>
      <div>
        <h4>Date :</h4>
        <%= l event.seance.horaire, format: :short %>
      </div>
      <div>
        <h4>Film :</h4>
        <%= event.seance.film.title %>
      </div>
      <% end %>
      <div class="show-event">
        <% #= link_to "Réserver !", event.seance.link, target: "_blank", class: "btn bungee btn-primary" if event.seance %>
        <% #= link_to "Répondre !", answer_path(event), class: "btn bungee btn-primary" if !event.seance %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/pages/no_film.html.erb
<div class="error-card">
<h1 class="color2 bungee mb-4">Désolés !</h1>
<h2 class="my-4">Aucun film ne correspond à votre recherche ...</h2>
<h3 class="my-4">Essayez d'élargir votre plage horaire, ou d'ajouter plus de films à vos favoris</h3>
<p class="my-4">Ou alors .. Changez d'amis ! 😃</p>
<div>
<%= link_to "Organiser une nouvelle sortie", new_event_path, class: "btn btn-primary bungee" %>
</div>
<div class="my-4">
<%= link_to "Ajouter de nouveaux films a mes favoris", favorites_path, class: "btn btn-primary bungee" %>
</div>
</div>